# Generated by Django 5.0.2 on 2024-07-14 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='president_candidate',
        ),
        migrations.AddField(
            model_name='candidate',
            name='resident',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vice_presidents', to='election.candidate'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='election.category'),
        ),
    ]
