# Generated by Django 5.0.2 on 2024-07-14 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0002_remove_candidate_president_candidate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='resident',
        ),
    ]
