# Generated by Django 5.0.2 on 2024-07-19 16:01

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0003_remove_candidate_resident'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='voting_end',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='voting_start',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 19, 16, 1, 6, 634722, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
