# Generated by Django 5.0.2 on 2024-07-19 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0004_category_voting_end_category_voting_start'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='voting_end',
        ),
        migrations.RemoveField(
            model_name='category',
            name='voting_start',
        ),
    ]
