# Generated by Django 5.0.2 on 2024-07-20 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0006_category_voting_end_time_category_voting_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='webauthn_credential_id',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='webauthn_public_key',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='webauthn_sign_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
