# Generated by Django 5.0.2 on 2024-07-20 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0007_student_webauthn_credential_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='webauthn_credential_id',
        ),
        migrations.RemoveField(
            model_name='student',
            name='webauthn_public_key',
        ),
        migrations.RemoveField(
            model_name='student',
            name='webauthn_sign_count',
        ),
    ]
