# Generated by Django 5.0.2 on 2024-07-20 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0008_remove_student_webauthn_credential_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vote',
            old_name='timestamp',
            new_name='voting_timestamp',
        ),
    ]
