# Generated by Django 5.0.2 on 2024-07-20 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0009_rename_timestamp_vote_voting_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectionSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='XYZ University Election', max_length=255)),
            ],
        ),
    ]
